name: core_control_panel
description: A new Flutter project.
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  snippet_coder_utils: ^1.0.13
  http: ^0.13.5
  qlevar_router: ^1.9.0
  shared_preferences: ^2.1.1
  jwt_decode: ^0.3.1
  cupertino_icons: ^1.0.5
  json_editor: ^0.0.8
  google_fonts: ^4.0.4
  universal_html: ^2.2.2
  web_socket_channel: ^2.4.0
  chess: ^0.7.0
  flutter_chess_board: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true